botforge.chat.persona=astrid
botforge.chat.objective=astrid
botforge.chat.max-words=50
urbbot.chat.llm.model=gpt-4.1-mini
botforge.chat.llm.temperature=1.38
botforge.chat.memory-eager-limit=50
botforge.chat.tagline=Your friendly neighbourhood astrologer
botforge.chat.show-prompts=true

botforge.mcp-tools-description=use for web search

botforge.bot-packages=com.embabel.bot.astrid

botforge.stylesheet=astrid
