package org.legendstack.basebot.tools;

import com.embabel.agent.api.annotation.LlmTool;
import com.embabel.agent.api.annotation.UnfoldingTools;
import org.legendstack.basebot.user.BotForgeUserService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import org.springframework.stereotype.Service;

/**
 * Enterprise architecture tools for structured deliverables:
 * ADRs, architecture review checklists, and C4 diagrams.
 */
@UnfoldingTools(name = "architectureReviewTools", description = "Tools for generating ADRs, architecture reviews, and C4 diagrams")
@Service
public class ArchitectureReviewTool {

    private static final Logger logger = LoggerFactory.getLogger(ArchitectureReviewTool.class);
    private static final String DESIGNS_DIR = "workspace/designs";

    private final BotForgeUserService userService;

    public ArchitectureReviewTool(BotForgeUserService userService) {
        this.userService = userService;
    }

    @LlmTool(description = """
            Generate and save a structured Architectural Decision Record (ADR) in the MADR format.
            Use this when a significant architectural decision has been discussed and needs to be documented.
            The ADR captures the context, decision, and consequences for future reference.

            Parameters:
            - title: Short decision title, e.g. "Use Kafka for event streaming"
            - context: Why this decision is needed — business drivers, constraints, forces at play
            - decision: The chosen approach and rationale
            - alternatives: Other options that were considered and why they were rejected
            - consequences: Positive and negative impacts of this decision
            """)
    public String generateADR(String title, String context, String decision,
            String alternatives, String consequences) {
        try {
            var user = userService.getAuthenticatedUser();
            String teamId = user.getTeamId();
            String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmm"));
            String sanitized = title.replaceAll("[^a-zA-Z0-9]", "_").toLowerCase();

            String adrContent = String.format("""
                    # ADR: %s

                    **Date:** %s
                    **Status:** Proposed
                    **Author:** %s (via Architect Assistant)

                    ## Context

                    %s

                    ## Decision

                    %s

                    ## Alternatives Considered

                    %s

                    ## Consequences

                    ### Positive
                    %s

                    ### Risks & Mitigations
                    _(To be reviewed by architecture team)_

                    ---
                    _Generated by BotForge Architect Assistant_
                    """,
                    title,
                    LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE),
                    user.getUsername(),
                    context,
                    decision,
                    alternatives,
                    consequences);

            Path dir = Paths.get(DESIGNS_DIR, teamId, "adr");
            Files.createDirectories(dir);
            String fileName = String.format("ADR_%s_%s.md", timestamp, sanitized);
            Path filePath = dir.resolve(fileName);
            Files.writeString(filePath, adrContent);

            logger.info("Generated ADR for team {}: {}", teamId, filePath);
            return "✅ ADR published to: " + filePath.toAbsolutePath()
                    + "\n\nThe ADR is in 'Proposed' status and ready for architecture team review.";
        } catch (IOException e) {
            logger.error("Failed to generate ADR", e);
            return "Error generating ADR: " + e.getMessage();
        }
    }

    @LlmTool(description = """
            Run a structured 12-point architecture review checklist against a component or system design.
            Use this to provide a comprehensive assessment before a formal architecture review.
            Returns a structured report with pass/warn/fail for each dimension.

            Parameters:
            - componentName: Name of the component or system being reviewed
            - description: Detailed description of the architecture being assessed
            - scalingRequirements: Expected load, users, throughput (optional — pass empty string if unknown)
            - securityContext: Security and compliance constraints (optional — pass empty string if unknown)
            """)
    public String runArchitectureChecklist(String componentName, String description,
            String scalingRequirements, String securityContext) {
        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME);

        String report = String.format("""
                # Architecture Review Checklist: %s

                **Date:** %s
                **Component:** %s

                ## Assessment Dimensions

                | # | Dimension | Status | Notes |
                |---|-----------|--------|-------|
                | 1 | **Scalability** | ⏳ Needs Assessment | %s |
                | 2 | **High Availability** | ⏳ Needs Assessment | Single points of failure? Failover strategy? |
                | 3 | **Security & AuthN/AuthZ** | ⏳ Needs Assessment | %s |
                | 4 | **Data Consistency** | ⏳ Needs Assessment | CAP trade-offs? Eventual vs strong consistency? |
                | 5 | **Observability** | ⏳ Needs Assessment | Metrics, logging, tracing, alerting? |
                | 6 | **Deployment Strategy** | ⏳ Needs Assessment | Blue-green? Canary? Rollback plan? |
                | 7 | **Cost Optimization** | ⏳ Needs Assessment | Resource right-sizing? Reserved vs on-demand? |
                | 8 | **API Design** | ⏳ Needs Assessment | Versioning? Rate limiting? Contract testing? |
                | 9 | **Error Handling** | ⏳ Needs Assessment | Circuit breakers? Retry policies? DLQ? |
                | 10 | **Data Governance** | ⏳ Needs Assessment | PII handling? Retention? Backup/restore? |
                | 11 | **Testing Strategy** | ⏳ Needs Assessment | Integration tests? Load tests? Chaos engineering? |
                | 12 | **Team Readiness** | ⏳ Needs Assessment | Skills? On-call? Runbooks? |

                ## Description Under Review

                %s

                ---

                ### Next Steps
                1. Walk through each dimension with the developer
                2. Update status to ✅ Pass / ⚠️ Warn / ❌ Fail
                3. Generate ADR for key decisions using `generateADR`
                4. Publish final report using `publishDesignDoc`

                _Generated by BotForge Architect Assistant_
                """,
                componentName,
                timestamp,
                componentName,
                scalingRequirements.isEmpty() ? "Not specified — ask about expected load" : scalingRequirements,
                securityContext.isEmpty() ? "Not specified — ask about auth and compliance" : securityContext,
                description);

        logger.info("Generated architecture checklist for: {}", componentName);
        return report;
    }

    @LlmTool(description = """
            Generate a C4-model Mermaid diagram for visualizing system architecture.
            Use this to create visual architecture diagrams at different abstraction levels.

            Parameters:
            - systemName: Name of the system being diagrammed
            - level: C4 level — "context" (L1: system + external actors), "container" (L2: deployed units), or "component" (L3: internal structure)
            - components: Comma-separated list of key components/containers to include in the diagram
            - description: Brief description of the system for the diagram title
            """)
    public String generateC4Diagram(String systemName, String level, String components, String description) {
        String[] parts = components.split(",");
        StringBuilder mermaid = new StringBuilder();

        mermaid.append("```mermaid\ngraph TB\n");
        mermaid.append(String.format("    title[\"%s — C4 %s Diagram\"]\n",
                systemName, capitalize(level)));

        switch (level.toLowerCase()) {
            case "context" -> {
                mermaid.append("    User((\"👤 User\"))\n");
                mermaid.append(String.format("    System[\"%s\"]\n", systemName));
                for (String part : parts) {
                    String id = sanitizeId(part.trim());
                    mermaid.append(String.format("    %s[\"%s\"]\n", id, part.trim()));
                    mermaid.append(String.format("    System --> %s\n", id));
                }
                mermaid.append("    User --> System\n");
            }
            case "container" -> {
                mermaid.append(String.format("    subgraph %s[\"%s\"]\n", sanitizeId(systemName), systemName));
                for (String part : parts) {
                    String id = sanitizeId(part.trim());
                    mermaid.append(String.format("        %s[\"%s\"]\n", id, part.trim()));
                }
                mermaid.append("    end\n");
            }
            case "component" -> {
                mermaid.append(String.format("    subgraph %s[\"%s Internals\"]\n",
                        sanitizeId(systemName), systemName));
                mermaid.append("        direction TB\n");
                for (String part : parts) {
                    String id = sanitizeId(part.trim());
                    mermaid.append(String.format("        %s[\"%s\"]\n", id, part.trim()));
                }
                mermaid.append("    end\n");
            }
        }

        mermaid.append("```\n\n");
        mermaid.append(String.format("**%s**: %s\n\n", systemName, description));
        mermaid.append("> 💡 This is a starting point. Ask me to add connections, data flows, ");
        mermaid.append("or expand specific containers into component-level detail.");

        logger.info("Generated C4 {} diagram for: {}", level, systemName);
        return mermaid.toString();
    }

    private static String sanitizeId(String s) {
        return s.replaceAll("[^a-zA-Z0-9]", "_");
    }

    private static String capitalize(String s) {
        return s.isEmpty() ? s : Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }
}
